"""Backlog seeded from Software Development Blueprint — StickerKiosk (Draft 0.1)."""

BLUEPRINT_PATH = "docs/blueprint/stickerkiosk-blueprint.md"

ISSUES = [
    {
        "id": "FR-001",
        "title": "[FR-001] Chọn model whitelist và sticker pre-cut",
        "type": "Feature",
        "priority": "P1 High",
        "area": "kiosk-ui",
        "risk": "Low",
        "iteration": "MVP-1",
        "context": (
            "Khách kiosk không được giả định có kiến thức kỹ thuật. MVP chỉ phục vụ 3–5 model lưng phẳng "
            "trên whitelist cố định. Sticker phải pre-cut và khớp template model. Model mới = fixture/profile mới, "
            "không nhận diện AI."
        ),
        "scope": (
            "In: danh sách model whitelist, SKU sticker khớp template, chặn SKU không khớp, copy tiếng Việt. "
            "Out: artwork tùy biến, in/cắt tại kiosk, model ngoài list."
        ),
        "acceptance": [
            "Given whitelist đã cấu hình, when khách chọn một model, then chỉ hiện SKU sticker khớp model đó.",
            "Given SKU không thuộc template model đang chọn, when khách cố chọn, then hệ thống từ chối và không tạo QR.",
            "Given model không nằm trong whitelist, when khách tìm model đó, then kiosk từ chối — không gọi AI detect.",
        ],
        "dependency": "Q-002 (danh sách 3–5 model). A-002 (có hàng sticker). FR-015.",
        "risk_detail": "Chọn nhầm model làm so khớp profile sai → reject hoặc dán lệch. Mitigation: UI nhấn mạnh model đã chọn trước khi trả tiền.",
        "blueprint_anchor": "fr-001",
    },
    {
        "id": "FR-002",
        "title": "[FR-002] Preview giá, thời lượng và cảnh báo an toàn trước khi insert",
        "type": "Feature",
        "priority": "P1 High",
        "area": "kiosk-ui",
        "risk": "Medium",
        "iteration": "MVP-1",
        "context": (
            "Khách sẽ không giao máy nếu không thấy giá, thời lượng, hướng dẫn tháo ốp/lau lưng, và cảnh báo an toàn "
            "trước khi máy vào khay."
        ),
        "scope": (
            "In: màn preview bắt buộc, xác nhận của khách, chặn mở khay nhận máy nếu chưa ack. "
            "Out: tư vấn miệng của nhân viên thay cho preview."
        ),
        "acceptance": [
            "Given đã chọn model+SKU, when vào bước preview, then hiện giá, thời lượng dự kiến, hướng dẫn tháo ốp/lau, cảnh báo an toàn bằng tiếng Việt.",
            "Given khách chưa xác nhận preview, when hệ thống kiểm tra insert-ready, then không cho mở khay nhận máy.",
            "Given copy thiếu một trường bắt buộc, when tạo QR, then API trả lỗi và không charge.",
        ],
        "dependency": "FR-001, FR-004, FR-015, C-005.",
        "risk_detail": "Bỏ qua cảnh báo → tranh chấp khi xước/kẹt (R-001). Mitigation: ack tường minh, ghi audit.",
        "blueprint_anchor": "fr-002",
    },
    {
        "id": "FR-003",
        "title": "[FR-003] Thanh toán QR paid/failed/unknown — charge trước",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "payment",
        "risk": "High",
        "iteration": "MVP-2",
        "context": (
            "Một rail QR. Charge trước rồi mới cho insert. Cổng trả paid/failed/unknown. Không mô tả hold/authorization "
            "trừ khi cổng được chọn thực sự hỗ trợ. Không lưu dữ liệu thẻ."
        ),
        "scope": (
            "In: tạo order id, hiện QR, poll/webhook, hết hạn QR, chống double charge. "
            "Out: đa cổng, card, ví khác, loyalty."
        ),
        "acceptance": [
            "Given preview đã ack, when tạo QR, then order có id ổn định và state AwaitingPayment.",
            "Given cổng báo paid, when kiosk xác nhận, then Payment.localStatus=Paid và không tạo charge thứ hai với cùng idempotency key.",
            "Given cổng báo failed hoặc QR hết hạn, when khách chưa Paid, then không insert và không start.",
            "Given cổng báo unknown, when chưa có Decision Q-004, then không start applicator.",
        ],
        "dependency": "A-003 (sandbox QR). Q-004. FR-014. NFR-006. NFR-008.",
        "risk_detail": "R-002: unknown sau khi khách đã quét. Cấm apply khi chưa Paid xác nhận.",
        "blueprint_anchor": "fr-003",
    },
    {
        "id": "FR-004",
        "title": "[FR-004] Chặn đưa máy vào khay khi đơn chưa Paid",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "payment",
        "risk": "High",
        "iteration": "MVP-2",
        "context": "Applicator chỉ được phép chạy khi job Paid và khay Locked. Insert trước khi Paid phá giả thuyết an toàn/tài chính.",
        "scope": "In: cổng Paid trên UI và API insert-ready. Out: hold/authz giả nếu cổng không hỗ trợ.",
        "acceptance": [
            "Given order không ở Paid, when khách tới bước đặt máy, then UI không mở khay nhận máy và giải thích tiếng Việt.",
            "Given API-004 insert-ready, when order chưa Paid, then 403 và không đổi state sang AwaitingInsert.",
        ],
        "dependency": "FR-003, FR-007.",
        "risk_detail": "Nhân viên bypass bằng hardware — vẫn không được start nếu controller kiểm Paid+Locked (FR-007).",
        "blueprint_anchor": "fr-004",
    },
    {
        "id": "FR-005",
        "title": "[FR-005] Đóng và khóa khay trước khi apply",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": "Khay phải đóng và khóa trước khi dán. locked là tín hiệu từ controller local, không phải chỉ UI.",
        "scope": "In: lệnh lock, đọc status.locked, từ chối start nếu chưa locked. Out: thiết kế cơ khí chi tiết của khóa.",
        "acceptance": [
            "Given so khớp profile pass, when gửi start, then controller từ chối nếu locked=false.",
            "Given lock thành công, when GET status, then locked=true và AuditLog ghi chuyển sang Locked.",
            "Given lock thất bại, when retry, then không start và UI bảo chờ nhân viên nếu không recover.",
        ],
        "dependency": "FR-006, FR-007, FR-018.",
        "risk_detail": "Khách rút máy giữa chu kỳ. Mitigation: không start khi chưa locked; E-stop (FR-010).",
        "blueprint_anchor": "fr-005",
    },
    {
        "id": "FR-006",
        "title": "[FR-006] So khớp profile model đã chọn — không AI detect",
        "type": "Feature",
        "priority": "P1 High",
        "area": "apply-quality",
        "risk": "High",
        "iteration": "MVP-4",
        "context": (
            "Cảm biến/camera so vị trí và kích thước với profile model khách đã chọn. Từ chối nếu lệch, sai size, "
            "còn ốp, hoặc vật cản. Không đoán model."
        ),
        "scope": "In: pose/size/case/obstruction vs profile đã chọn. Out: AI classifier model, lưng cong/foldable.",
        "acceptance": [
            "Given khách chọn model A, when máy/ốp không khớp profile A, then reject, mở khay trả máy, không start.",
            "Given phát hiện vật cản hoặc case-on, when check chạy, then fail với reason code và log.",
            "Given không có model nào được 'đoán', when inspect telemetry, then không có nhánh auto-detect model.",
        ],
        "dependency": "FR-001, Q-002, FR-018.",
        "risk_detail": "False pass → dán lệch (R-005). False reject → hoàn/refund niềm tin. Lab hiệu chỉnh ngưỡng trước trial.",
        "blueprint_anchor": "fr-006",
    },
    {
        "id": "FR-007",
        "title": "[FR-007] Controller local chỉ start khi Paid và Locked",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": (
            "Controller kiosk local là lớp duy nhất được lệnh applicator. Backend và app khách không được start. "
            "start chỉ từ flow kiosk đã Paid+Locked."
        ),
        "scope": "In: enforcement Paid+Locked+!eStop trên API-007. Out: robot công nghiệp đầy đủ.",
        "acceptance": [
            "Given Paid=false hoặc Locked=false hoặc eStop=true, when POST /controller/start, then 403/409 và applicator không chuyển động.",
            "Given request start từ nguồn không phải kiosk local flow, when controller nhận, then từ chối và log.",
            "Given start hợp lệ, when idempotency key trùng, then không chạy apply lần hai.",
        ],
        "dependency": "FR-003, FR-005, FR-018, NFR-010.",
        "risk_detail": "Lệnh từ xa khi mất ngữ cảnh an toàn. Mitigation: controller không expose start ra internet.",
        "blueprint_anchor": "fr-007",
    },
    {
        "id": "FR-008",
        "title": "[FR-008] Pass QC thì mở khay và hoàn tất đơn",
        "type": "Feature",
        "priority": "P1 High",
        "area": "apply-quality",
        "risk": "Medium",
        "iteration": "MVP-4",
        "context": "Đường thành công: dán xong, so khớp/QC đạt, mở khay, khách lấy máy, order Completed.",
        "scope": "In: unlock sau pass, copy lấy máy tiếng Việt, đóng job. Out: auto-pass camera nếu Q-003 chưa chốt — mặc định có thể pass theo sensor apply complete + staff photo (Assumption).",
        "acceptance": [
            "Given ApplyJob result=Passed, when controller unlock, then khay mở và UI hướng dẫn lấy máy bằng tiếng Việt.",
            "Given khách lấy máy (tray empty), when session đóng, then Order=Completed và stock SKU giảm 1 (idempotent).",
            "Given Q-003 chưa Decision, when hoàn tất, then không nhận 'AI đẹp/xấu' làm điều kiện ẩn.",
        ],
        "dependency": "FR-006, Q-003, FR-015.",
        "risk_detail": "Mở khay khi QC chưa xong. Mitigation: unlock chỉ sau Passed.",
        "blueprint_anchor": "fr-008",
    },
    {
        "id": "FR-009",
        "title": "[FR-009] Fail/fault: giữ máy an toàn và gọi nhân viên",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": "Khi fail hoặc fault, khay giữ điện thoại an toàn, màn hình bảo khách chờ nhân viên, mở yêu cầu hỗ trợ/hoàn phí dịch vụ.",
        "scope": "In: FailedHold, UI wait-for-staff, tạo RefundRequest/support. Out: bồi thường giá trị máy, bảo hiểm.",
        "acceptance": [
            "Given apply/QC/hardware fault, when job fail, then motion stop, khay không nhả tự động, Order=FailedHold.",
            "Given FailedHold, when UI khách render, then copy tiếng Việt bảo chờ nhân viên — không hướng dẫn tự cạy khay.",
            "Given fail, when hệ thống ghi, then có support/refund request gắn order id.",
        ],
        "dependency": "FR-010, FR-011, FR-013, FR-016, NFR-004.",
        "risk_detail": "R-001, R-004. Không trial máy thật nếu không có người trực (NFR-005).",
        "blueprint_anchor": "fr-009",
    },
    {
        "id": "FR-010",
        "title": "[FR-010] E-stop và mất tín hiệu an toàn cắt chuyển động",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": "E-stop cắt motion. Mất safety signal thì dừng. Không resume apply tự động.",
        "scope": "In: eStop status, stop path, log, UI. Out: chứng nhận CE/PCCC (site).",
        "acceptance": [
            "Given đang Applying, when E-stop nhấn, then motion=false trong ngưỡng thời gian harness (đo trong spec phần cứng).",
            "Given mất safety signal, when controller detect, then stop và state Estopped/SafeHold.",
            "Given eStop đã kích, when có lệnh start, then từ chối đến khi staff reset có audit.",
        ],
        "dependency": "FR-018, Q-007, NFR-004.",
        "risk_detail": "E-stop không dây hoặc UI-only. Constraint: E-stop phải cắt motion ở controller/hardware, không chỉ dừng animation.",
        "blueprint_anchor": "fr-010",
    },
    {
        "id": "FR-011",
        "title": "[FR-011] Mở khóa thủ công ủy quyền và luôn ghi audit",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "staff-console",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": "Mở khóa thủ công chỉ nhân viên ủy quyền. Mọi lần mở log: ai, khi nào, order id, lý do. Sau mất điện vẫn lấy máy được bằng cơ khí ủy quyền.",
        "scope": "In: API-009, audit, role operator. Out: khách tự unlock.",
        "acceptance": [
            "Given caller không phải operator, when POST /staff/unlock, then 403.",
            "Given unlock thành công, when đọc AuditLog, then có actor, timestamp, orderId, reason, action=manual_unlock.",
            "Given mất điện, when dùng mở cơ khí ủy quyền, then khi hệ thống lên phải ghi recovery event (không được im lặng).",
        ],
        "dependency": "FR-012, FR-013, NFR-010.",
        "risk_detail": "Credential staff chia sẻ. Mitigation: tài khoản cá nhân, revoke được.",
        "blueprint_anchor": "fr-011",
    },
    {
        "id": "FR-012",
        "title": "[FR-012] Recovery mất điện, mất mạng, UI treo — không kẹp, không mất order, không double charge",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-3",
        "context": "Power loss, network loss, hung UI phải để máy và khay an toàn. Chi tiết recovery thuộc spec; intent bắt test trước acceptance.",
        "scope": "In: local persistence order id, idempotent payment, safe clamp policy, UI reconnect. Out: cluster đa kiosk.",
        "acceptance": [
            "Given mất điện giữa Applying, when kiểm tra, then máy lấy ra được qua unlock ủy quyền; không kẹp phá máy.",
            "Given mất mạng sau Paid local, when mạng lên, then ledger sync idempotent — không charge lần hai.",
            "Given UI treo, when watchdog, then controller không start mới; order id không bị xóa.",
        ],
        "dependency": "FR-003, FR-011, NFR-008, C-007.",
        "risk_detail": "Hung UI vẫn gửi start lặp. Mitigation: idempotency + controller state.",
        "blueprint_anchor": "fr-012",
    },
    {
        "id": "FR-013",
        "title": "[FR-013] Console nhân viên: fault, unlock, hoàn phí, restock, vệ sinh",
        "type": "Feature",
        "priority": "P1 High",
        "area": "staff-console",
        "risk": "Medium",
        "iteration": "MVP-5",
        "context": "Operator xử lý sự cố, mở khóa, xác nhận hoàn phí dịch vụ, restock sticker, đánh dấu vệ sinh.",
        "scope": "In: các hành động trên cho role operator. Out: POS mall, lịch ca phức tạp.",
        "acceptance": [
            "Given FaultEvent Open, when operator mở console, then thấy kiosk id, order id (nếu có), code, severity.",
            "Given operator restock, when lưu, then stockQty tăng và audit ghi.",
            "Given đánh dấu vệ sinh, when lưu, then có timestamp — không giả làm QC apply.",
        ],
        "dependency": "FR-011, FR-016, FR-001 stock.",
        "risk_detail": "Console lộ trên mạng công cộng. Mitigation: chỉ LAN/kiosk staff login (NFR-010).",
        "blueprint_anchor": "fr-013",
    },
    {
        "id": "FR-014",
        "title": "[FR-014] Sổ cái giao dịch và log chuyển trạng thái append-only",
        "type": "Feature",
        "priority": "P1 High",
        "area": "ledger-audit",
        "risk": "High",
        "iteration": "MVP-1",
        "context": "Mọi tranh chấp máy/thanh toán cần kiosk id, order id, timestamp, reason. Ledger không sửa im lặng.",
        "scope": "In: AuditLog + Order state events. Out: analytics marketing.",
        "acceptance": [
            "Given mọi chuyển state Order/Payment/ApplyJob/Unlock/Refund, when commit, then có event kioskId, orderId, at, actor, from, to, reason.",
            "Given attempt sửa event cũ, when API, then bị từ chối (append-only).",
            "Given mất mạng, when sync, then không mất event local đã ghi.",
        ],
        "dependency": "NFR-008, FR-012.",
        "risk_detail": "Thiếu log khi khách cáo buộc xước (R-001) → không bảo vệ được nhóm.",
        "blueprint_anchor": "fr-014",
    },
    {
        "id": "FR-015",
        "title": "[FR-015] UI khách và copy lỗi tiếng Việt cho người lạ",
        "type": "Feature",
        "priority": "P1 High",
        "area": "kiosk-ui",
        "risk": "Medium",
        "iteration": "MVP-1",
        "context": "Customer UI và error copy bằng tiếng Việt, người lạ tại site thử dùng được. Phải có empty/loading/error/wait-for-staff.",
        "scope": "In: toàn bộ màn khách. Out: i18n đa ngôn ngữ MVP.",
        "acceptance": [
            "Given từng màn chính (chọn, preview, QR, insert, applying, collect, wait-for-staff), when review, then không còn copy tiếng Anh bắt buộc để hoàn tất.",
            "Given lỗi cổng/khay/timeout, when hiện, then có hành động tiếp theo rõ (thử lại / chờ nhân viên / hủy).",
            "Given empty catalog hoặc hết SKU, when vào chọn mẫu, then empty state tiếng Việt, không màn trắng.",
        ],
        "dependency": "FR-001–FR-009.",
        "risk_detail": "Người lạ bỏ cuộc giữa chừng → gãy giả thuyết self-service (BR-003).",
        "blueprint_anchor": "fr-015",
    },
    {
        "id": "FR-016",
        "title": "[FR-016] Hoàn phí dịch vụ theo chính sách — staff xác nhận (mặc định)",
        "type": "Feature",
        "priority": "P1 High",
        "area": "staff-console",
        "risk": "High",
        "iteration": "MVP-5",
        "context": (
            "MVP: giữ máy an toàn + gọi staff + hoàn phí dịch vụ. Không bảo hiểm giá trị máy. "
            "Mặc định nhân viên bấm hoàn sau khi đọc log; hoàn tự động = Open Question Q-005."
        ),
        "scope": "In: RefundRequest mode=service-fee, idempotent. Out: payout giá trị thiết bị.",
        "acceptance": [
            "Given FailedHold, when tạo refund request, then amount = phí dịch vụ đã thu, không phải giá máy.",
            "Given operator xác nhận, when cổng refund thành công, then Order=Refunded một lần (idempotent).",
            "Given Q-005 chưa Decision auto, when fail code xảy ra, then không tự refund.",
        ],
        "dependency": "FR-003, FR-009, Q-005, A-006.",
        "risk_detail": "Double refund hoặc hoàn nhầm. Mitigation: idempotency key + ledger.",
        "blueprint_anchor": "fr-016",
    },
    {
        "id": "FR-017",
        "title": "[FR-017] Console chủ dịch vụ: giao dịch, fault, doanh thu, sức khỏe máy",
        "type": "Feature",
        "priority": "P2 Medium",
        "area": "staff-console",
        "risk": "Low",
        "iteration": "MVP-5",
        "context": "Service owner cần transactions, faults, revenue, machine health — không PII khách.",
        "scope": "In: dashboard đọc ledger. Out: BI đa kiosk rollout.",
        "acceptance": [
            "Given role owner, when mở console, then thấy đếm order, doanh thu phí dịch vụ, fault mở, controllerHealth.",
            "Given dữ liệu khách, when inspect API, then không có tên, SĐT, ảnh mặt.",
        ],
        "dependency": "FR-014, NFR-006.",
        "risk_detail": "Nhầm lẫn doanh thu với bồi thường máy — UI phải ghi 'phí dịch vụ'.",
        "blueprint_anchor": "fr-017",
    },
    {
        "id": "FR-018",
        "title": "[FR-018] Adapter phần cứng start/stop/status/locked/error và simulator",
        "type": "Feature",
        "priority": "P0 Critical",
        "area": "hardware-adapter",
        "risk": "High",
        "iteration": "MVP-1",
        "context": (
            "Applicator là module qua interface tối thiểu. Phải chọn module trước khi khóa spec. "
            "Không giả định tự chế robot cả kỳ. Simulator bắt buộc khi hardware chưa sẵn (R-003)."
        ),
        "scope": "In: adapter + simulator cùng contract. Out: thiết kế công nghiệp đầy đủ.",
        "acceptance": [
            "Given simulator, when start/stop/status/locked/error, then UI kiosk hoàn tất happy path không cần máy thật.",
            "Given hardware adapter, when cùng contract, then controller không nhánh UI riêng (chỉ config).",
            "Given error từ module, when status.error set, then không start và FR-009 kích hoạt.",
        ],
        "dependency": "Q-001, A-001, R-003.",
        "risk_detail": "Hardware muộn → chỉ test được BR-003 (UI), không test BR-001/002. Issue này bắt buộc simulator để không bịa 'đã an toàn'.",
        "blueprint_anchor": "fr-018",
    },
    {
        "id": "NFR-004",
        "title": "[NFR-004] Nghiệm thu lab: 0 xước/nứt/kẹt không lấy được máy",
        "type": "Task",
        "priority": "P0 Critical",
        "area": "safety-controller",
        "risk": "Critical",
        "iteration": "MVP-4",
        "context": "Ngưỡng lab (Assumption, không SLA thương mại): zero scratch/crack/unrecoverable-jam trong lab acceptance.",
        "scope": "In: checklist nghiệm thu + evidence. Out: chứng nhận an toàn mall.",
        "acceptance": [
            "Given harness lab, when chạy kịch bản E-stop, mất điện, jam giả lập, then máy luôn lấy ra được và log đủ.",
            "Given phát hiện xước/nứt/kẹt không lấy được, when review, then NFR fail — không trial tình nguyện viên.",
        ],
        "dependency": "FR-010, FR-011, FR-012, NFR-005.",
        "risk_detail": "R-001. Đây là cổng bắt buộc trước máy thật.",
        "blueprint_anchor": "nfr-004",
    },
    {
        "id": "NFR-006",
        "title": "[NFR-006] Không hồ sơ khách, không dữ liệu thẻ — định danh = order id",
        "type": "Task",
        "priority": "P1 High",
        "area": "privacy-ops",
        "risk": "Medium",
        "iteration": "MVP-2",
        "context": "Constraint privacy: không customer profile, không card data. Transaction identifier = order id.",
        "scope": "In: data review payment + order. Out: tài khoản loyalty.",
        "acceptance": [
            "Given storage schema, when review, then không có bảng khách hàng hay trường PAN/CVV/tên chủ thẻ.",
            "Given payment adapter, when persist, then chỉ provider ref + status, không raw QR chứa PII nếu cổng trả về.",
        ],
        "dependency": "FR-003, FR-014, FR-017.",
        "risk_detail": "Lộ dữ liệu thanh toán. Mitigation: tối thiểu hóa.",
        "blueprint_anchor": "nfr-006",
    },
    {
        "id": "NFR-007",
        "title": "[NFR-007] Ảnh QC có retention, chỉ phục vụ sự cố, không nhận diện người",
        "type": "Task",
        "priority": "P1 High",
        "area": "privacy-ops",
        "risk": "High",
        "iteration": "MVP-4",
        "context": "Ảnh lưng máy nếu lưu chỉ cho incident review, có retention, không dùng nhận diện người. Thời hạn = Q-006.",
        "scope": "In: QcImage storedUntil + purge. Out: gallery marketing.",
        "acceptance": [
            "Given bật lưu ảnh, when insert QcImage, then bắt buộc storedUntil — thiếu thì API-012 400.",
            "Given hết hạn, when job purge, then bytes xóa và bản ghi Purged.",
            "Given codebase, when search, then không có face/person recognition.",
        ],
        "dependency": "Q-006. Default Assumption: không upload cloud công cộng đến khi Decision.",
        "risk_detail": "R-007.",
        "blueprint_anchor": "nfr-007",
    },
    {
        "id": "NFR-008",
        "title": "[NFR-008] An toàn chạy local khi mất mạng; ledger sync idempotent",
        "type": "Task",
        "priority": "P0 Critical",
        "area": "ledger-audit",
        "risk": "High",
        "iteration": "MVP-3",
        "context": "Lệnh máy và an toàn local. Business ledger sync khi mạng lên. Test mất mạng trước acceptance.",
        "scope": "In: local start path, queue sync. Out: multi-region.",
        "acceptance": [
            "Given đã Paid local, when mạng down, then controller vẫn enforce safety; không start nếu chưa Paid.",
            "Given event local, when mạng lên, then sync không nhân bản charge/refund.",
        ],
        "dependency": "FR-007, FR-012, FR-014.",
        "risk_detail": "Split-brain Paid. Mitigation: order id + idempotency.",
        "blueprint_anchor": "nfr-008",
    },
    {
        "id": "SP-001",
        "title": "[SP-001] Chốt module phần cứng và đóng băng API start/stop/locked/error",
        "type": "Spike",
        "priority": "P0 Critical",
        "area": "hardware-adapter",
        "risk": "High",
        "iteration": "MVP-0",
        "context": "Open Question Q-001: kit tự lắp, applicator có sẵn, hay đối tác gia công? API phải đóng băng trước khi khóa spec.",
        "scope": "In: so sánh phương án, đề xuất một, hạn đóng băng. Out: chế robot hoàn chỉnh trong spike.",
        "acceptance": [
            "Given spike xong, when ghi Decision, then có module được chọn, owner, ngày đóng băng contract FR-018.",
            "Given không chọn được module trong nửa đầu kỳ, when báo cáo, then kế hoạch simulator-only được giảng viên biết — không nhận đã test BR-001/002.",
        ],
        "dependency": "A-001, C-011, FR-018.",
        "risk_detail": "R-003 Hardware muộn.",
        "blueprint_anchor": "q-001",
    },
    {
        "id": "SP-002",
        "title": "[SP-002] Chốt 3–5 model whitelist lưng phẳng phổ biến tại Việt Nam",
        "type": "Spike",
        "priority": "P1 High",
        "area": "apply-quality",
        "risk": "Medium",
        "iteration": "MVP-0",
        "context": "Q-002. iPhone Pro Max chỉ là ví dụ, không phải quyết định.",
        "scope": "In: danh sách model, fixture, nguồn sticker. Out: mọi SKU thị trường.",
        "acceptance": [
            "Given spike xong, when cập nhật blueprint, then DeviceModel whitelist 3–5 tên cụ thể + nguồn fixture.",
            "Given model có lưng cong/foldable, when đề xuất, then bị loại khỏi MVP.",
        ],
        "dependency": "A-002, FR-001, FR-006.",
        "risk_detail": "Chọn model khó fixture → trễ Increment 4.",
        "blueprint_anchor": "q-002",
    },
    {
        "id": "SP-003",
        "title": "[SP-003] Camera sau dán: auto pass/fail hay chỉ lưu ảnh cho staff",
        "type": "Spike",
        "priority": "P2 Medium",
        "area": "apply-quality",
        "risk": "Medium",
        "iteration": "MVP-4",
        "context": "Q-003. Ảnh có rủi ro retention (Q-006).",
        "scope": "In: Decision + impact lên FR-008/NFR-007. Out: research computer vision dài hạn.",
        "acceptance": [
            "Given Decision auto-QC, when ghi, then có ngưỡng đo được và owner sai số.",
            "Given Decision staff-only photo, when ghi, then apply complete không block bởi vision; ảnh tuân NFR-007.",
        ],
        "dependency": "Q-006, NFR-007, FR-008.",
        "risk_detail": "Auto-QC sai → nhả máy lỗi hoặc giữ máy oan.",
        "blueprint_anchor": "q-003",
    },
    {
        "id": "SP-004",
        "title": "[SP-004] Payment unknown: giữ đối soát hay từ chối apply",
        "type": "Spike",
        "priority": "P0 Critical",
        "area": "payment",
        "risk": "High",
        "iteration": "MVP-2",
        "context": "Q-004 / R-002. Intent: không apply khi chưa Paid. Cần Decision vận hành khi cổng unknown.",
        "scope": "In: Decision + luồng UI/ledger. Out: viết lại cổng QR.",
        "acceptance": [
            "Given Decision, when cập nhật FR-003/UC-002, then hành vi unknown testable (hold tray vs refuse apply).",
            "Given mọi phương án, when apply, then start vẫn cấm khi localStatus != Paid.",
        ],
        "dependency": "FR-003, A-003.",
        "risk_detail": "Apply khi chưa Paid hoặc từ chối khách đã trả. Phải có đối soát thủ công.",
        "blueprint_anchor": "q-004",
    },
    {
        "id": "SP-005",
        "title": "[SP-005] Hoàn phí: nhân viên xác nhận hay tự động theo mã lỗi",
        "type": "Spike",
        "priority": "P1 High",
        "area": "staff-console",
        "risk": "Medium",
        "iteration": "MVP-5",
        "context": "Q-005. Blueprint mặc định staff confirm cho đến khi Decision khác.",
        "scope": "In: Decision. Out: cổng bảo hiểm.",
        "acceptance": [
            "Given Decision staff-only, when fail, then FR-016 giữ nguyên.",
            "Given Decision auto, when ghi, then danh sách fault code được hoàn tự động và vẫn idempotent.",
        ],
        "dependency": "FR-016, A-006.",
        "risk_detail": "Auto-refund khi chưa rõ lỗi phần cứng vs khách rút máy.",
        "blueprint_anchor": "q-005",
    },
    {
        "id": "SP-006",
        "title": "[SP-006] Chính sách lưu/xóa ảnh QC (thời hạn, local/cloud)",
        "type": "Spike",
        "priority": "P1 High",
        "area": "privacy-ops",
        "risk": "High",
        "iteration": "MVP-4",
        "context": "Q-006 / R-007. Assumption tạm: không cloud công cộng, đề xuất 14 ngày — chưa Decision.",
        "scope": "In: retention policy + chỗ lưu. Out: hệ thống DL đầy đủ.",
        "acceptance": [
            "Given Decision, when cập nhật NFR-007, then storedUntil rule + nơi lưu + cách xóa có owner.",
            "Given chưa Decision, when implement, then không bật upload ảnh lên cloud công cộng.",
        ],
        "dependency": "NFR-007, Q-003.",
        "risk_detail": "Lưu ảnh lưng máy vô hạn.",
        "blueprint_anchor": "q-006",
    },
    {
        "id": "SP-007",
        "title": "[SP-007] Chốt site thử và roster trực E-stop/unlock",
        "type": "Spike",
        "priority": "P1 High",
        "area": "privacy-ops",
        "risk": "High",
        "iteration": "MVP-0",
        "context": "Q-007 / NFR-005 / R-004 / R-006. Site đầu: lab, sảnh, hoặc một quầy. Phải có người trực khi dùng máy thật.",
        "scope": "In: tên site, roster, giờ. Out: hợp đồng thuê mall dài hạn.",
        "acceptance": [
            "Given Decision site, when ghi, then địa điểm + người chịu E-stop watch theo ca.",
            "Given không có roster, when đề xuất trial máy tình nguyện viên, then bị chặn (NFR-005).",
        ],
        "dependency": "NFR-005, R-006.",
        "risk_detail": "Mall chặn trước khi có prototype an toàn.",
        "blueprint_anchor": "q-007",
    },
]
